version: "3.9"
services:
  postgres:
    image: postgres:15-alpine3.19
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  messenger:
    image: messenger:0.0.1
    build:
      dockerfile: Dockerfile
      context: ../
    entrypoint:
      - /usr/local/bin/messenger
    environment:
      - HTTP_PORT=9080
      - PG_PASSWORD=password
    ports:
      - "9080:9080"
    depends_on:
      postgres:
        condition: service_healthy