#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE TABLE MAILINGS(
  ID SERIAL PRIMARY KEY,
  IS_SCHEDULED BOOLEAN DEFAULT FALSE,
  CREATED_AT TIMESTAMP DEFAULT NOW()
);

CREATE TABLE CUSTOMERS(
  ID SERIAL PRIMARY KEY,
  EMAIL VARCHAR(100) UNIQUE
);

CREATE TABLE MESSAGES(
  ID SERIAL PRIMARY KEY,
  MAILING_ID integer REFERENCES MAILINGS,
  CUSTOMER_ID integer REFERENCES CUSTOMERS,
  TITLE VARCHAR(100),
  CONTENT VARCHAR(5000)
);

EOSQL